project:
  type: website
  output-dir: "docs"

website:
  title: "nateraw.com"
  twitter-card: true
  favicon: favicon.ico
  site-url: "https://www.nateraw.com"
  navbar:
    right:
      - icon: github
        href: https://github.com/nateraw/
      - icon: twitter
        href: https://twitter.com/_nateraw
      - icon: linkedin
        href: https://www.linkedin.com/in/Nathan-Raw/
  google-analytics: G-QQ37HV1W85

ipynb-filters:
  - filter.py

format:
  html:
    theme: lux
    page-layout: full

execute:
  freeze: auto

resources:
  - CNAME
  - static/training_musicgen_songstarter/*.wav