project:
  type: website
  output-dir: "docs"

website:
  title: "nateraw.com"
  twitter-card: true
  favicon: favicon.ico
  site-url: "https://www.nateraw.com"
  navbar:
    right:
      - icon: github
        href: https://github.com/nateraw/
      - icon: twitter
        href: https://twitter.com/_nateraw
      - icon: linkedin
        href: https://www.linkedin.com/in/Nathan-Raw/

  # If you fork this, use a different google analytics id or remove this line
  google-analytics: G-JZN5RBFRD7

ipynb-filters:
  - filter.py

format:
  html:
    theme: lux
    page-layout: full

execute:
  freeze: auto

resources:
  - CNAME
  - static/training_musicgen_songstarter/*.wav
  - static/training_musicgen_songstarter/bach.mp3
  - static/training_musicgen_songstarter/kalhonaho_trap_base_model.mp3
  - static/training_musicgen_songstarter/bach_guitar_base_model.mp3
  - static/training_musicgen_songstarter/singing_songstarter_v2.mp4